// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package query

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Article struct {
	ID        string
	AuthorID  pgtype.Text
	Title     pgtype.Text
	Body      pgtype.Text
	CreatedAt pgtype.Timestamp
}

type Author struct {
	ID   string
	Name pgtype.Text
}
